version: 2

sources:
  - name: nyc_raw
    database: xw-cis-9440
    schema: nyc_hw3_raw_data

    tables:
      - name: source_dot_service_requests_history
      - name: source_nyc_open_restaurant_apps