name: 'nyc_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_analytics:

    

    # ===== HW keep=====
    assignment_work:
      staging:
        +materialized: table
        +schema: nyc_transit_restaurants_staging

      marts:
        +materialized: table
        +schema: nyc_transit_restaurants_marts

    # =====  Milestone 4 Project =====
    project_group15:

      staging:
        +materialized: table
        +schema: nyc_school_staging

      marts:
        +materialized: table
        +schema: nyc_school_marts